version: "3.8"

services:
  gateway:
    container_name: gateway
    build: ./gateway
    volumes:
      - ./gateway:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    networks:
      - ms-movies

  ms-users:
    container_name: ms-users
    build: ./ms-users
    volumes:
      - ./ms-users:/app
      - /app/node_modules
    ports:
      - "8001:8001"
    networks:
      - ms-movies

  ms-movies:
    depends_on:
      - db-ms-movies
    container_name: ms-movies
    build: ./ms-movies
    volumes:
      - ./ms-movies:/app
      - /app/node_modules
    ports:
      - "8002:8002"
    networks:
      - ms-movies

  db-ms-movies:
    image: postgres:14.3
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - ms-movies

networks:
  ms-movies:
    driver: bridge
